### ISSUE TITLE
Can't reproduce the result in paper

### ISSUE THREAD

**Issue by ljwztc** [BUserName/PGL#4]
Hello, we run you code according to the README but we can't reproduce the result in your paper. And the OS of VisDA17 is only 66.3. So VisDA18 is. Could you please give more detailed training information?

**Comment by BUserName** [comment]
Hi there,

Tooks some time to validate the results of VisDA18.  Please try the following command to reproduce the results.
```
python train.py -b=6 -a=res --threshold=0.1 --EF=5
```

If you meet the CUDA out of memory error (just like I do, too lazy to roll back the original environment), just add the following code to line 288 of the model_trainer.py file
```
with torch.no_grad():
```

I will investigate Visda17 later on.

Please let me know if you still encounter any problems!

**Comment by ljwztc** [comment]
Thanks so much for the quick response. According to the hyper-parameter you offered, the results of VisDA18 is comparable with he results reported in paper. And I use the same setting to run the VisDA17 but find unsatisfactory results. May I known the meaning of EF hyper-parameters? and does this parameter influence the training most?
Moreover, I find the performance will drop severely when the batch size is enlarged to 8 for VisDA18.

**Comment by BUserName** [comment]
Lol. You must have several V100 GPUs then :D  Never had a chance to try batch size 8 for visda18 yet, limited by my 2080ti GPUs.

EF parameter here defines what percentage of samples will be pseudo-labeled at the end of each step. If EF is relatively large, it will label more 'less confident' samples at the early stage. This may lead to error accumulation and negative transfer. While a smaller EF reduces the fault rate of the pseudo-labeling process, it inevitably requires more running time/epochs. This is a trade-off existing in our algorithm.

Hope the above comment helps, and thanks again for your interest in our work!
