### ISSUE TITLE
Where can I download the appendix of the paper?

### ISSUE THREAD

**Issue by jingzhengli** [BUserName/PGL#5]
HI, Where can I download the appendix of the paper? Could you please provide the download link?

**Comment by BUserName** [comment]
Hi Jingzheng,

Please check the following link for the supplementary material.
http://proceedings.mlr.press/v119/luo20b/luo20b-supp.pdf

**Comment by jingzhengli** [comment]
> Hi Jingzheng,
> 
> Please check the following link for the supplementary material. http://proceedings.mlr.press/v119/luo20b/luo20b-supp.pdf

Got it, thanks
